"""empty message

Revision ID: c38e6ce8d6cb
Revises: cf1cbaa0a5bb
Create Date: 2022-02-07 18:33:05.290300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c38e6ce8d6cb'
down_revision = 'cf1cbaa0a5bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('leader_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'leader_id')
    # ### end Alembic commands ###
